{
 "title": "Battery Health",
 "tags": [
  "tesla",
  "teslaCustom"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select  preferred_range from settings;"
   },
   {
    "name": "battery_capacity",
    "query": "WITH lastCharges AS (\n\tSELECT (100.0 * charge_energy_added) / (end_battery_level - start_battery_level)\n\tFROM charging_processes\n\tWHERE \n\t\tcharge_energy_added >= 10\n\t\tAND car_id = $car_id\n\tORDER BY end_date DESC\n\tLIMIT 5\n)\nSELECT * FROM lastCharges \nORDER BY 1 DESC\nLIMIT 1"
   },
   {
    "name": "degradation",
    "query": "SELECT AVG(data.degradation) FROM\n(\n\tSELECT 100 - convert_km(((end_rated_range_km * 100.0)/(end_battery_level * $max_range / 100.0)), '$length_unit')::float as degradation\n\tFROM charging_processes \n\tWHERE \n\t\tcar_id = $car_id \n\t\tAND end_date IS NOT NULL \n\t\tAND charge_energy_added > 10 \n\tORDER BY end_date DESC  \n\tLIMIT 5\n) AS data\n"
   },
   {
    "name": "max_range",
    "query": "WITH projected_range AS (\n\tSELECT\n\t\t$__timeGroup(date, 1d) AS time,\n\t\tconvert_km((sum(rated_battery_range_km) / nullif(sum(coalesce(usable_battery_level, battery_level)),0) * 100)::numeric, '$length_unit') AS \"Projected rated range [$length_unit]\"\n\tFROM\n\t\t(\n\t\t\tSELECT \n\t\t\t\tbattery_level, usable_battery_level, date, rated_battery_range_km\n    \t\tFROM positions\n    \t\tWHERE\n\t\t\t\tcar_id = $car_id\n\t\t\t\tAND ideal_battery_range_km IS NOT null\n    \t\tUNION ALL\n    \t\t\tSELECT \n\t\t\t\t\tbattery_level, coalesce(usable_battery_level, battery_level) as usable_battery_level, date, rated_battery_range_km\n\t\t    \tFROM charges c\n    \t\t\tJOIN\n      \t\t\t\tcharging_processes p ON p.id = c.charging_process_id \n    \t\t\tWHERE\n       \t\t\t\tp.car_id = $car_id\n    \t) AS data\n\tGROUP BY 1\n\tHAVING convert_km((sum(rated_battery_range_km) / nullif(sum(coalesce(usable_battery_level, battery_level)),0) * 100)::numeric, '$length_unit') IS NOT null\n\tORDER BY 2 DESC\n\tLIMIT 1\n)\nSELECT \"Projected rated range [$length_unit]\" FROM projected_range "
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated battery capacity",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n\t$__timeGroup(date, 1M) AS time,\n\tconvert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') \n\t* ($battery_capacity + ($battery_capacity * $degradation / 100.0)) / $max_range AS \"kWh\"\nFROM\n\t(\n    SELECT \n      battery_level, usable_battery_level, date, rated_battery_range_km, ideal_battery_range_km, outside_temp\n    FROM positions\n    WHERE\n      car_id = $car_id \n      AND $__timeFilter(date) \n      AND ideal_battery_range_km is not null\n    UNION ALL\n    SELECT \n      battery_level, coalesce(usable_battery_level,battery_level) as usable_battery_level, date, \n      rated_battery_range_km, ideal_battery_range_km, outside_temp\n    FROM charges c\n    JOIN\n      charging_processes p ON p.id = c.charging_process_id \n    where\n      $__timeFilter(date) \n      AND p.car_id = $car_id\n    ) AS data\nGROUP BY 1\nHAVING \n  convert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') IS NOT NULL\nORDER BY 1, 2  DESC"
    }
   ]
  },
  {
   "title": "Estimated degradation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  $degradation as \"Degradation\""
    }
   ]
  },
  {
   "title": "Battery Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  (100 - $degradation) as \"Battery Health (%)\""
    }
   ]
  },
  {
   "title": "Current battery level",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT last(\"soc\") FROM \"ovms\" WHERE $timeFilter",
     "rawSql": "(SELECT usable_battery_level, date\n  FROM positions\n  WHERE car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n)\nUNION\n  SELECT usable_battery_level, date\n  FROM charges c\n  JOIN charging_processes p ON p.id = c.charging_process_id\n  WHERE $__timeFilter(date) AND p.car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "ovms_v_b_soc" }
     ]
    }
   ]
  },
  {
   "title": "Current range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), range as \"range_$length_unit\"\nFROM (\n\t(SELECT date, convert_km(rated_battery_range_km, '$length_unit') AS range\n\tFROM positions\n\tWHERE car_id = $car_id AND rated_battery_range_km IS NOT NULL\n  ORDER BY date DESC\n\tLIMIT 1)\n\tUNION ALL\n\t(SELECT date, convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS range\n\tFROM charges c\n\tJOIN charging_processes p ON p.id = c.charging_process_id\n\tWHERE p.car_id = $car_id\n\tORDER BY date DESC\n\tLIMIT 1)\n) AS data\nORDER BY date DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Current battery capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  $battery_capacity AS battery_capacity"
    }
   ]
  },
  {
   "title": "Current capacity",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "(\n  SELECT date, usable_battery_level * $battery_capacity / 100 as kWh\n  FROM positions\n  WHERE car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n)\nUNION\nSELECT date, usable_battery_level * $battery_capacity / 100 as kWh\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id\nWHERE $__timeFilter(date) AND p.car_id = $car_id\nORDER BY date DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT  \n  $battery_capacity AS battery_capacity"
    }
   ]
  },
  {
   "title": "Current MAX range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), (range * 100.0 / battery_level) as \"max_range_$length_unit\"\nFROM (\n\t(SELECT date, convert_km(rated_battery_range_km, '$length_unit') AS range, usable_battery_level as battery_level\n\tFROM positions\n\tWHERE car_id = $car_id AND rated_battery_range_km IS NOT NULL\n  ORDER BY date DESC\n\tLIMIT 1)\n\tUNION ALL\n\t(SELECT date, convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS range, usable_battery_level as battery_level\n\tFROM charges c\n\tJOIN charging_processes p ON p.id = c.charging_process_id\n\tWHERE p.car_id = $car_id\n\tORDER BY date DESC\n\tLIMIT 1)\n) AS data\nORDER BY date DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Projected Range - Mileage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\t$__timeGroup(date, 6h) AS time,\n\tconvert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') AS \"Projected [[preferred_range]] range [$length_unit]\"\nFROM\n\t(\n    select battery_level, usable_battery_level, date,\n      rated_battery_range_km, ideal_battery_range_km, outside_temp\n    from positions\n    where\n      car_id = $car_id and $__timeFilter(date) and ideal_battery_range_km is not null\n    union all\n    select battery_level, coalesce(usable_battery_level,battery_level) as usable_battery_level, date,\n      rated_battery_range_km, ideal_battery_range_km, outside_temp\n    from charges c\n    join\n      charging_processes p ON p.id = c.charging_process_id \n    where\n      $__timeFilter(date) and p.car_id = $car_id\n    ) as data\n\nGROUP BY\n\t1\nhaving convert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') is not null\nORDER BY\n\t1,2  DESC"
    },
    {
     "rawSql": "SELECT\n\t$__timeGroup(date, 6h) AS time,\n\tconvert_km(avg(odometer)::numeric, '$length_unit') AS \"Mileage [$length_unit]\"\nFROM\n\tpositions\nWHERE\n\t$__timeFilter(date) and\n\tcar_id = $car_id  and ideal_battery_range_km is not null\nGROUP BY\n\t1\nORDER BY\n\t1,2  DESC;"
    }
   ]
  }
 ]
}