{
 "title": "Drive Tops",
 "tags": [
  "tesla",
  "teslaCustom"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   { "name": "min_avg_speed", "label": "Minimum average speed", "query": "50" }
  ]
 },
 "panels": [
  {
   "title": "Median distance of a drive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT convert_km((percentile_disc(0.5) WITHIN GROUP (ORDER BY distance))::numeric, '$length_unit') as \"distance_$length_unit\"\nFROM drives\nWHERE car_id = $car_id AND $__timeFilter(start_date);"
    }
   ]
  },
  {
   "title": "Median distance driven per day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH since as (\n\tSELECT date FROM positions\n\tWHERE car_id = $car_id\n\tORDER BY date ASC\n\tLIMIT 1\n),\nactual AS (\n\tSELECT\n\t\tdate_trunc('day', start_date)::date AS date,\n\t\tsum(distance) AS distance\n\tFROM drives\n\tWHERE car_id = $car_id\n\tGROUP BY 1\n),\nbase_line AS (\n\tSELECT date_trunc('day', dd)::date AS date\n  FROM generate_series((select date from since), NOW(), '1 day'::interval) dd\n),\ncombined as (\n  SELECT base_line.date, COALESCE(actual.distance, 0) as distance\n  FROM base_line\n  LEFT JOIN actual ON actual.date = base_line.date\n  WHERE $__timeFilter(base_line.date)\n)\nSELECT convert_km((percentile_disc(0.5) WITHIN GROUP (ORDER BY distance))::numeric, '$length_unit') AS \"distance_$length_unit\"\nFROM combined;"
    }
   ]
  },
  {
   "title": "Extrapolated monthly mileage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH first_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date ASC\n\tLIMIT 1\n),\nlast_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date DESC\n\tLIMIT 1\n)\nSELECT\n\tconvert_km((((SELECT odometer FROM last_position) - (SELECT odometer\tFROM first_position)) /\n\tEXTRACT(days FROM (SELECT date FROM last_position) - (SELECT date\tFROM first_position)) * \n\t(365/12))::numeric, '$length_unit') AS \"mileage_$length_unit\";"
    }
   ]
  },
  {
   "title": "Extrapolated annual mileage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH first_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date ASC\n\tLIMIT 1\n),\nlast_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date DESC\n\tLIMIT 1\n)\nSELECT\n\tconvert_km(((lp.odometer - fp.odometer) /\n\tEXTRACT(days FROM lp.date - fp.date) * \n\t365)::numeric, '$length_unit') AS \"mileage_$length_unit\" from first_position as fp, last_position as lp;"
    }
   ]
  },
  {
   "title": "Max distance traveled between recharges",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH c AS (\n\tSELECT *, COALESCE(LAG(start_date) OVER(ORDER BY start_date DESC), now()) AS next_start_date \n\tFROM charging_processes\n\tWHERE car_id = $car_id\n),\nrng AS (\n\tSELECT\n\t\tdate,\n\t\tdistance,\n\t\tduration_min,\n\t \tmax_battery_level,\n\t\tmin_battery_level\n\tFROM (\n\t\tSELECT d.start_date AS date, d.distance, d.duration_min, MAX(p.battery_level) AS max_battery_level, MIN(p.battery_level) AS min_battery_level\n\t\tFROM drives d\n\t\tLEFT JOIN positions p ON p.drive_id = d.id\n\t\tWHERE \n\t\t\td.car_id = $car_id\n\t\t\tAND $__timeFilter(d.start_date)\n\t\tGROUP BY 1, 2, 3\n\t\tHAVING COUNT(p.id) > 0\n\t) AS data\n\tGROUP BY 1, 2, 3, 4, 5\n),\nfnd AS (\n\tSELECT\n\t\tc.end_date,\n\t\tc.next_start_date,\n\t\tCOALESCE(SUM(r.distance), 0) AS distance_driven,\n\t\tCOALESCE(SUM(r.duration_min), 0) AS duration_min,\n\t\tr.max_battery_level,\n\t\tr.min_battery_level\n\tFROM c c\n\tLEFT JOIN rng r ON r.date BETWEEN c.start_date and c.next_start_date\n\tGROUP BY 1, 2, 5, 6\n)\nSELECT \n\t(round(extract(epoch FROM end_date) - 10) * 1000) AS start_date_ts,\n\t(round(extract(epoch FROM next_start_date) + 10) * 1000) AS end_date_ts,\n\tend_date, next_start_date,\n\tCASE WHEN (duration_min / 60) > 0\n\t\tTHEN convert_km((distance_driven / (duration_min::numeric / 60))::numeric, '$length_unit')\n\t\tELSE 1\n\tEND AS avg_speed_[[length_unit]]h,\n\t(max_battery_level - min_battery_level)AS battery_needed,\n\tconvert_km(distance_driven::decimal, '$length_unit') AS \"Distance driven\"\nFROM fnd\nWHERE (distance_driven / ((round(extract(epoch FROM next_start_date)) - round(extract(epoch FROM end_date))) / 3600)) > $min_avg_speed\nORDER BY distance_driven DESC\nLIMIT 17"
    }
   ]
  },
  {
   "title": "Distance per years",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 6, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT to_char(end_date,'YYYY') as \"Year\",\r\n       convert_km((sum(distance))::numeric, '$length_unit') as \"Distance\"\r\nFROM drives\r\nWHERE \r\n  car_id = $car_id\r\nGROUP BY 1\r\nORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "AVG speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT \n\t\tdistance / ((round(extract(epoch FROM end_date)) - round(extract(epoch FROM start_date))) / 3600) AS avg_speed\n\tFROM drives\n\tWHERE \n\t\tdistance > 1\n\t\tAND car_id = $car_id\n)\nSELECT convert_km(AVG(avg_speed)::numeric, '$length_unit') AS avg_speed_[[length_unit]]h\nFROM data"
    }
   ]
  },
  {
   "title": "AVG speed - Last 10 drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT \n\t\tdistance / ((round(extract(epoch FROM end_date)) - round(extract(epoch FROM start_date))) / 3600) AS avg_speed\n\tFROM drives\n\tWHERE \n\t\tdistance > 1\n\t\tAND car_id = $car_id\n\tORDER BY start_date DESC\n\tLIMIT 10\n)\nSELECT convert_km(AVG(avg_speed)::numeric, '$length_unit') AS avg_speed_[[length_unit]]h\nFROM data"
    }
   ]
  },
  {
   "title": "Last 12 months",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT to_char(end_date,'YY-MM') as \"Date\",\r\n       convert_km((SUM(distance))::numeric, '$length_unit') as \"Distance\"\r\nFROM drives\r\nWHERE \r\n  $__timeFilter(end_date)\r\n  AND car_id = $car_id\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Average distance per month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT to_char(end_date,'MM') as \"month_n\",\n\t\tto_char(end_date,'YY') as \"year_n\",\n       to_char(end_date,'Month') as \"month\",\n       SUM(distance)::numeric as \"distance\"\n\tFROM drives\n\tWHERE \n\t  car_id = $car_id\n\t  AND distance > 0\n\tGROUP BY 1, 2, 3\n\tORDER BY 1\n)\nSELECT \n\td.month_n as \"month_number\",\n\td.month as \"Month\",\n\tconvert_km(AVG(d.distance)::numeric, '$length_unit') as \"Distance\"\nFROM data d\nGROUP BY 1, 2\nORDER BY 1 ASC"
    }
   ]
  }
 ]
}